### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by 911wb** [YWL0720/YOLO_ORB_SLAM3#1]
你好请问可以结合双目IMU和YOLOV5吗？可以开源学习以下吗？感谢@！

**Comment by YWL0720** [comment]
这里其实只是用了yolo的接口在构造每帧图像后进行行人识别，保存识别到的行人区域信息，提取FAST角点后，将位于行人区域的特征点删除。双目IMU模式也是可以按照这个思路来改的。不知道有没有你想要了解的东西。我也是初学者
