### ISSUE TITLE
编译通过但运行报错

### ISSUE THREAD

**Issue by yzli1998** [YWL0720/YOLO_ORB_SLAM3#12]
代码编译通过了，但是运行时报了以下错误，请问是什么原因呢？
Pass 'Combine redundant instructions' is not initialized.
Verify if there is a pass dependency cycle.
Required Passes:
段错误 (核心已转储)

我使用的第三方库的版本和你的一样，但ubuntu是18.04。

**Comment by yzli1998** [comment]
更换Libtorch版本后已解决

**Comment by dkfmpdgv** [comment]
> 更换Libtorch版本后已解决

请问更换的是哪个版本的呀，可以提供以下链接吗，太谢谢你了

**Comment by yyanzzw** [comment]
请问更换的版本是什么呢？请问您的其他库版本都不用变吗

**Comment by yyanzzw** [comment]
> 更换Libtorch版本后已解决

请问更换的版本是什么呢？请问您的其他库版本都不用变吗

**Comment by yyanzzw** [comment]
> > 更换Libtorch版本后已解决
> 
> 
> 
> 请问更换的是哪个版本的呀，可以提供以下链接吗，太谢谢你了
> 
> 

哥，这个问题你解决了吗？

**Comment by YWL0720** [comment]
@yyanzzw 您好，建议使用百度网盘内分享的版本，readme中的系统配置经过测试是可以正常编译运行的

**Comment by yyanzzw** [comment]
> @yyanzzw 您好，建议使用百度网盘内分享的版本，readme中的系统配置经过测试是可以正常编译运行的

感谢您的回复！我刚刚跑通了tum 数据集，与您提供的版本区别在于：ubuntu18.04，opencv3.2，libtorch1.7.0。非常感谢您的代码！

**Comment by Ygang923** [comment]
> > @yyanzzw 您好，建议使用百度网盘内分享的版本，readme中的系统配置经过测试是可以正常编译运行的
> 
> 感谢您的回复！我刚刚跑通了tum 数据集，与您提供的版本区别在于：ubuntu18.04，opencv3.2，libtorch1.7.0。非常感谢您的代码！

> 您好 我用的百度链接下载LIbtorch依旧会出现
Pass 'Combine redundant instructions' is not initialized.
Verify if there is a pass dependency cycle.
Required Passes:
段错误 (核心已转储) 
这是什么原因呢

**Comment by BalveerSinghYT** [comment]
Hi @YWL0720

I'm also getting the same issue. Here are my configurations:
Ubuntu 20.04,
OpenCV 4.2.0
Libtorch 1.11.0+cpu


How can I get appropriate version of libtorch?

thank you :)
