### ISSUE TITLE
The issue pertains to running the TUM dataset.

### ISSUE THREAD

**Issue by xzh20000525** [YWL0720/YOLO_ORB_SLAM3#16]
Hello, I encountered an error while running the TUM dataset following your instructions. The error message is: "rgbd_tum: /tmp/llvm/lib/Support/BranchProbability.cpp:41: llvm::BranchProbability::BranchProbability(uint32_t, uint32_t): assumption 'Numerator <= Denominator && "Probability cannot be bigger than 1!"' failed." I'm not sure how to resolve this issue. If you have some time, could you please assist me? Thank you very much.

**Comment by YWL0720** [comment]
We conducted testing in the following environment and achieved successful results:
- Ubuntu 20.04
- ROS Noetic
- OpenCV 4.2
Furthermore, we recommend using the first method described in the README to install libtorch.
