### ISSUE TITLE
我使用的是opencv4.2的版本，但是会出现如下问题，请问你们都是怎么运行出来的

### ISSUE THREAD

**Issue by xjx954** [YWL0720/YOLO_ORB_SLAM3#17]
/home/xjx/YOLO_ORB_SLAM3/Thirdparty/DBoW2/DBoW2/FORB.h:13:10: fatal error: opencv2/core/core.hpp: 没有那个文件或目录

**Comment by YWL0720** [comment]
方便的话可以提供cmake输出的更多信息

**Comment by xjx954** [comment]
![image](https://github.com/YWL0720/YOLO_ORB_SLAM3/assets/110157255/114ed07f-ef84-434e-aeb2-6379d6b085b8)

**Comment by YWL0720** [comment]
CMakeLists.txt有更改么？

**Comment by xjx954** [comment]
我换了opencv的版本为3.4.3解决了该问题，谢谢！

**Comment by labourer-Lucas** [comment]
@xjx954 您好，请问opencv3.4能正常运行吗，我的运行回报错segmentantion fault (core dumped)

**Comment by xjx954** [comment]
你这个是段错误核心已转储，大概率是代码里的数组或者指针越界导致的，应该和opencv关系不大吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月9日(星期二) 下午2:22
收件人: ***@***.***&gt;; 
抄送: "all ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YWL0720/YOLO_ORB_SLAM3] 我使用的是opencv4.2的版本，但是会出现如下问题，请问你们都是怎么运行出来的 (Issue #17)














 
@xjx954 您好，请问opencv3.4能正常运行吗，我的运行回报错segmentantion fault (core dumped)
