### ISSUE TITLE
请问可以ROS实时运行吗

### ISSUE THREAD

**Issue by Z-star1** [YWL0720/YOLO_ORB_SLAM3#2]

**Comment by YWL0720** [comment]
在launch文件夹里提供了修改相机发布频率的launch文件，根据实际的话题名进行修改，降低相机发布频率到15hz，实际测试是可以实时运行的

**Comment by BigJiang123** [comment]
Can it not support a higher frequency, such as 30 Hz? Otherwise, it would not be practical in actual deployment.
