### ISSUE TITLE
You need C++14 to compile pytorch

### ISSUE THREAD

**Issue by juicyfan** [YWL0720/YOLO_ORB_SLAM3#9]
您好！想问下我在ubuntu18.04下编译时总是会在libtorch上报这个错，我采用了gcc7.5.0和gcc9.1.0均会报错，调了一天有点摸不着头脑了..想问下如何解决呢

**Comment by YWL0720** [comment]
请问是否可以提供一些详细的错误信息

**Comment by juicyfan** [comment]
谢谢！我改用ubuntu20.04后没有报错了，应该是gcc版本的问题
